version: "3.9"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${WIREGUARD_PATH}:/config
      - /lib/modules:/lib/modules
    ports:
      - 4001:4001
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  cardano-node:
      container_name: cardano-node-relay
      image: inputoutput/cardano-node
      volumes:
        - ${DATABASE_PATH}:/data
        - ${CONFIG_PATH}:/configuration
        - ${SOCKET_PATH}:/ipc
      network_mode: service:wireguard
      command: ["run", 
                "--config /configuration/config.json",
                "--topology /configuration/topology.json",
                "--host-addr 0.0.0.0",
                "--port 4001",
                "--database-path /data",
                "--socket-path /ipc/node.socket"]
