version: "3.9"

services:
    app:
        container_name: mochi_metadata
        image: metadata-server
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8084:8084"
            - "8083:8083"
            - "8082:8082"
            - "8081:8081"
            - "8080:8080"
            - "443:443"
