version: "3.9"

services:
    app:
        container_name: mochi_metadata
        image: poolmeta-server
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
            - "443:443"
