{
 "title": "Cardano: Application metrics v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cardano Last Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_byron_proxy_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int", "legendFormat": "{{alias}}" },
    { "expr": "cardano_node_metrics_epoch_int", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Cardano Last Block Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Service Restarts Per Hour",
   "type": "graph",
   "description": "Shows how many times cardano related services have been restarted within a 1 hour lookback window",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase(node_systemd_unit_state{name=~\"cardano.*|byron.*|explorer.*\",state=\"active\"}[1h:10s])) > 0",
     "legendFormat": "{{alias}}-{{name}}"
    }
   ]
  },
  {
   "title": "Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}