version: "3.9"

services:
    app:
        container_name: grafana
        image: grafana/grafana
        restart: unless-stopped
        network_mode: "host"
        # ports:
        #     - "3000:3000"
