version: "3.9"

services:
    app:
        container_name: node-exporter
        image: prom/node-exporter
        restart: unless-stopped
        network_mode: "host"
        pid: "host"
        volumes:
          - "/:/host:ro"
        command: ["--path.rootfs=/host"]
